# Generated by Django 4.1.7 on 2023-04-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_alter_author_options_alter_music_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="author",
        ),
        migrations.AddField(
            model_name="music",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="music.author",
                verbose_name="Исполнитель",
            ),
        ),
    ]
