# Generated by Django 4.1.7 on 2023-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_remove_music_author_music_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="music",
            options={
                "ordering": ["-id"],
                "verbose_name": "Песня",
                "verbose_name_plural": "Песни",
            },
        ),
    ]
