# Generated by Django 4.1.7 on 2023-04-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_alter_music_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="cover",
            field=models.ImageField(
                null=True, upload_to="uploads/%Y/%m/%d", verbose_name="Обложка"
            ),
        ),
    ]
