# Generated by Django 4.1.7 on 2023-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_music_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="cover",
            field=models.ImageField(
                default="default_note.jpg",
                null=True,
                upload_to="uploads/%Y/%m/%d",
                verbose_name="Обложка",
            ),
        ),
    ]
