# Generated by Django 4.1.7 on 2023-04-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_alter_music_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestSong",
            fields=[
                (
                    "music_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="music.music",
                    ),
                ),
            ],
            bases=("music.music",),
        ),
    ]
